### ISSUE TITLE
Add versioned soname?

### ISSUE THREAD

**Issue by matthoosier-garmin** [tomba/kmsxx#43]
I've been making a packaged copy of this library, and one thing I noticed is that its runtime shared library is just "libkms++.so". That makes the packaging systems a little bit unhappy -- normally they want to see the naked .so file live in the -dev package, with the symlink expanding to point at a versioned filename like "libmks++.so.0".

I know that there's probably no interest in making an officially stable API here, but would it be acceptable to retrofit the CMake usage here so that the ELF library gets a "versioned" (in name only -- it'd still be understood to be unstable) filename to conform a little better with package managers?

**Comment by tomba** [comment]
No objections. It's something I have not looked at all yet, as, as you guessed, I haven't had any interest in creating a stable API, and even less, ABI.

However, are you sure you want to use dynamic lib? Perhaps you are, as you're asking for this =). But in my opinion, it's much easier to just link statically and be done with it, without any future headaches.

That said, if you build the python bindings, it'll always create a .so. Which is not versioned either...

**Comment by matthoosier-garmin** [comment]
I agree with you that for many applications, static linking is logistically simpler. In embedded systems, though, using a dynamic lib tends to make the license auditing a lot more manageable. I'll try to prep something in the next couple days, if that works for you.

**Comment by tomba** [comment]
Ah I see. Mozilla Public License 2.0 should be pretty open, though. But yes, I get the point, and as I said, no objections.

**Comment by matthoosier-garmin** [comment]
I was looking at the Python bindings cmake file, and it looks to me like that one should be left unversioned (because it's a loadable Python module, I think)??

**Comment by matthoosier-garmin** [comment]
See PR #44.

**Comment by matthoosier-garmin** [comment]
Solved with PR #44.
