### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_default_mode'

### ISSUE THREAD

**Issue by Robin329** [tomba/kmsxx#71]
Why do I report the following error when I run the script under py/tests?

```log
kmsxx$ python3 py/tests/test.py 
Traceback (most recent call last):
  File "/data/workspace/kmsxx/py/tests/test.py", line 22, in <module>
    mode = conn.get_default_mode()
AttributeError: 'NoneType' object has no attribute 'get_default_mode'
```

**Comment by tomba** [comment]
'conn' is None, i.e. the script didn't find any connectors.

**Comment by Robin329** [comment]
@tomba Thanks.

My board is indeed not connected to the connector, this error confuses me?

```log
kmsxx$ kmsprint 
Connector 0 (197) HDMI-A-1 (disconnected)
  Encoder 1 (196) TMDS
Connector 1 (211) HDMI-A-2 (disconnected)
  Encoder 2 (210) TMDS
Connector 2 (225) DP-1 (disconnected)
  Encoder 3 (224) TMDS
```

**Comment by tomba** [comment]
The test uses ResourceManager.reserve_connector(), which, if given no connector name, looks for connected connectors. So it returns None if you have nothing connected. The test.py script doesn't handle that case as it's just a simple test/example script.

**Comment by Robin329** [comment]
@tomba Thanks.
